plugins:
  - jekyll-polyglot
  - jekyll-minifier
languages:                   ["en", "es", "de", "it", "fr"]
default_lang:                "en"
exclude_from_localization:   ["assets", "images", "css", "README.md", "manifest.json", "humans.txt", "sitemap.xml"]
parallel_localization:       true
a_rootpage:                  "https://jamulus.io"
githubrepoeditbase:          "https://github.com/jamulussoftware/jamulussoftware.github.io/edit/changes"
exclude:                     ["README.md", "Gemfile.lock", "Gemfile", "CONTRIBUTING.md"]
jekyll-minifier:
  remove_intertag_spaces:    true
  remove_spaces_inside_tags: true
  remove_multi_spaces:       true
  compress_json:             true
  exclude:                   "sitemap.xml"
