name: Jekyll site CI

on:
  push:
    branches: [ release, next-release ]
  pull_request:
    branches: [ release, next-release ]
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod a+w /srv/jekyll/Gemfile.lock && chmod 777 /srv/jekyll && jekyll build --future"
    - name: Zip Website
      run: zip -r ${{ github.workspace }}/website.zip _site/*
    - uses: actions/upload-artifact@v2
      name: Upload Website
      with:
        name: Website
        path: ${{ github.workspace }}/website.zip
        retention-days: 15
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
