name: Sync release to changes
on:
  push:
    branches:
      - 'changes'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge release -> changes
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: release
          target_branch: changes
          github_token: ${{ github.token }}
